### ISSUE TITLE
Multiple region detection

### ISSUE THREAD

**Issue by FransHk** [alphadadajuju/AMMA#1]
Hi, thank you for your great work. In the paper illustrations only a single tubelet is shown on-frame. Is this work capable of dealing with detecting multiple regions in a video? Thanks!

**Comment by alphadadajuju** [comment]
Thank you for your interest in our work.
Yes, the backbone of our work is an object detector (plus an online linker/tracker), hence our method is able to detect multiple regions (i.e., separate action instances) in a video.

**Comment by FransHk** [comment]
Great, thanks!
